[package]
name = "zk_sigRecover"
type = "bin"
authors = ["CX"]
version = "0.1.0"

[dependencies]
# ecrecover = { tag = "v1.0.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" }
